### ISSUE TITLE
The new version of the translation into Russian. NEW VERSION, 5.8.2

### ISSUE THREAD

**Issue by Slayf** [er-mo/MyPasswordsTranslations#18]
Hello. If you still need help in translation, I translated the new line. NEW VERSION, 5.8.2
[strings.txt](https://github.com/er-mo/MyPasswordsTranslations/files/276339/strings.txt)

**Comment by Slayf** [comment]
Excuse me, this is the last version of the translation. Thank you.
[strings.txt](https://github.com/er-mo/MyPasswordsTranslations/files/276342/strings.txt)

**Comment by er-mo** [comment]
The new file still does not have correct encoding. What editor are you using? Make sure your encoding is utf-8 to be consistent.
See [expected](https://www.dropbox.com/s/vaoxohcm9zmgdh2/expected.png?dl=0) encoding.
See [yours](https://www.dropbox.com/s/qxk2o7vhzr3q2z8/yours.png?dl=0).
